"""Add stripe_fee_eur column

Revision ID: 20fcb5ead4ff
Revises: 4e9dff43c6d4
Create Date: 2026-01-24 16:22:13.439892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20fcb5ead4ff'
down_revision: Union[str, None] = '4e9dff43c6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # On dit à SQL : "Mets 0.0 pour les lignes existantes"
    op.add_column('recharges', sa.Column('stripe_fee_eur', sa.Float(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recharges', 'stripe_fee_eur')
    # ### end Alembic commands ###
