"""Ajout tables inventory et wallets

Revision ID: 4e9dff43c6d4
Revises: ec27f585a7ff
Create Date: 2026-01-24 02:10:20.409804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e9dff43c6d4'
down_revision: Union[str, None] = 'ec27f585a7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount_usdc', sa.Float(), nullable=False),
    sa.Column('recharge_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_reservations_expires_at'), 'inventory_reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_recharge_id'), 'inventory_reservations', ['recharge_id'], unique=False)
    op.add_column('recharges', sa.Column('amount_usdc_value', sa.Float(), nullable=False))
    op.add_column('recharges', sa.Column('amount_base_eur', sa.Float(), nullable=False))
    op.add_column('recharges', sa.Column('service_fee_eur', sa.Float(), nullable=False))
    op.add_column('recharges', sa.Column('vat_amount_eur', sa.Float(), nullable=False))
    op.add_column('recharges', sa.Column('total_paid_eur', sa.Float(), nullable=False))
    op.add_column('recharges', sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('recharges', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('recharges', 'units_granted',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_recharges_stripe_payment_intent_id'), 'recharges', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_recharges_user_id'), 'recharges', ['user_id'], unique=False)
    op.drop_constraint(op.f('recharges_user_id_fkey'), 'recharges', type_='foreignkey')
    op.create_foreign_key(None, 'recharges', 'users', ['user_id'], ['id'])
    op.drop_column('recharges', 'amount_usdc')
    op.drop_column('recharges', 'provider_reference')
    op.drop_column('recharges', 'date')
    op.drop_column('recharges', 'payment_provider')
    op.drop_column('recharges', 'amount_eur')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recharges', sa.Column('amount_eur', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('recharges', sa.Column('payment_provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recharges', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('recharges', sa.Column('provider_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recharges', sa.Column('amount_usdc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recharges', type_='foreignkey')
    op.create_foreign_key(op.f('recharges_user_id_fkey'), 'recharges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_recharges_user_id'), table_name='recharges')
    op.drop_index(op.f('ix_recharges_stripe_payment_intent_id'), table_name='recharges')
    op.alter_column('recharges', 'units_granted',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('recharges', 'created_at')
    op.drop_column('recharges', 'stripe_payment_intent_id')
    op.drop_column('recharges', 'total_paid_eur')
    op.drop_column('recharges', 'vat_amount_eur')
    op.drop_column('recharges', 'service_fee_eur')
    op.drop_column('recharges', 'amount_base_eur')
    op.drop_column('recharges', 'amount_usdc_value')
    op.drop_index(op.f('ix_inventory_reservations_recharge_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_expires_at'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    # ### end Alembic commands ###
