"""Initial migration

Revision ID: a72d494ec611
Revises: 
Create Date: 2026-01-14 03:52:36.630658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a72d494ec611'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recharges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount_eur', sa.Float(), nullable=False),
    sa.Column('amount_usdc', sa.Float(), nullable=False),
    sa.Column('units_granted', sa.Float(), nullable=False),
    sa.Column('payment_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='rechargestatus'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('provider_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('token_usage')
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('wallets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('wallets', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'SCA'::character varying"))
    op.alter_column('wallets', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint(op.f('wallets_circle_wallet_id_key'), 'wallets', type_='unique')
    op.create_index(op.f('ix_wallets_circle_wallet_id'), 'wallets', ['circle_wallet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_circle_wallet_id'), table_name='wallets')
    op.create_unique_constraint(op.f('wallets_circle_wallet_id_key'), 'wallets', ['circle_wallet_id'])
    op.alter_column('wallets', 'state',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('wallets', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'SCA'::character varying"))
    op.alter_column('wallets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'hashed_password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.create_table('token_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tokens_consumed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_usd', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('token_usage_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('token_usage_pkey'))
    )
    op.drop_table('recharges')
    # ### end Alembic commands ###
