"""Correction des relations entre les tables users wallets et recharges

Revision ID: fb83d54e412c
Revises: a72d494ec611
Create Date: 2026-01-14 14:49:07.477682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb83d54e412c'
down_revision: Union[str, None] = 'a72d494ec611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE userrole AS ENUM ('admin', 'user')")
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('admin', 'user', name='userrole'),
               existing_nullable=False,
               postgresql_using='role::userrole')
    op.create_unique_constraint(None, 'wallets', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # Drop the enum type
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
